import '../../../schema_parser/domain/models/project_schema.dart';
import '../../../schema_parser/domain/models/relationship_schema.dart';

class DbmlExporter {
  DbmlExporter._();

  static String export(ProjectSchema schema) {
    final buffer = StringBuffer();
    buffer.writeln('// Generated by Laravel ERD Generator');
    buffer.writeln('// Project: ${schema.projectName}');
    buffer.writeln();

    for (final table in schema.tables) {
      buffer.writeln('Table ${table.name} {');

      for (final col in table.columns) {
        final type = _mapType(col.type, col.length);
        final settings = <String>[];

        if (col.isPrimaryKey) settings.add('pk');
        if (col.autoIncrement) settings.add('increment');
        if (col.unique) settings.add('unique');
        if (!col.nullable && !col.isPrimaryKey) settings.add('not null');
        if (col.defaultValue != null) {
          settings.add("default: '${col.defaultValue}'");
        }

        final settingsStr =
            settings.isNotEmpty ? ' [${settings.join(', ')}]' : '';
        buffer.writeln('  ${col.name} ${type}$settingsStr');
      }

      buffer.writeln('}');
      buffer.writeln();
    }

    for (final rel in schema.relationships) {
      final refType = _refType(rel.type);
      buffer.writeln(
          'Ref: ${rel.sourceTable}.${rel.foreignKey ?? "${rel.sourceTable}_id"} $refType ${rel.targetTable}.${rel.localKey ?? "id"}');
    }

    if (schema.relationships.isNotEmpty) buffer.writeln();

    return buffer.toString();
  }

  static String _mapType(String type, int? length) {
    const map = {
      'id': 'bigint',
      'bigIncrements': 'bigint',
      'increments': 'int',
      'string': 'varchar',
      'text': 'text',
      'longText': 'text',
      'mediumText': 'text',
      'integer': 'int',
      'bigInteger': 'bigint',
      'smallInteger': 'int',
      'tinyInteger': 'int',
      'boolean': 'boolean',
      'date': 'date',
      'datetime': 'datetime',
      'timestamp': 'timestamp',
      'json': 'json',
      'float': 'float',
      'double': 'double',
      'decimal': 'decimal',
      'binary': 'binary',
      'uuid': 'uuid',
      'char': 'char',
    };
    final base = map[type] ?? type;
    if (length != null && (type == 'string' || type == 'varchar')) {
      return '$base($length)';
    }
    return base;
  }

  static String _refType(RelationshipType type) {
    switch (type) {
      case RelationshipType.belongsTo:
        return '>';
      case RelationshipType.hasMany:
        return '<';
      case RelationshipType.hasOne:
        return '<';
      case RelationshipType.belongsToMany:
        return '<>';
    }
  }
}
