import '../../../schema_parser/domain/models/project_schema.dart';

class MarkdownExporter {
  MarkdownExporter._();

  static String export(ProjectSchema schema) {
    final buffer = StringBuffer();
    final now = DateTime.now();

    buffer.writeln('# ${schema.projectName} - Data Dictionary');
    buffer.writeln();
    buffer.writeln(
      '**Generated:** ${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')} ${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')}',
    );
    buffer.writeln();
    buffer.writeln('---');
    buffer.writeln();

    buffer.writeln('## Summary');
    buffer.writeln();
    buffer.writeln('| Metric | Count |');
    buffer.writeln('|--------|-------|');
    buffer.writeln('| Tables | ${schema.tables.length} |');
    buffer.writeln('| Total Columns | ${schema.totalColumns} |');
    buffer.writeln('| Relationships | ${schema.relationships.length} |');
    buffer.writeln(
      '| Migration FKs | ${schema.relationshipsFromMigrations.length} |',
    );
    buffer.writeln(
      '| Model Inferred | ${schema.relationshipsFromModels.length} |',
    );
    buffer.writeln();
    buffer.writeln('---');
    buffer.writeln();

    buffer.writeln('## Tables');
    buffer.writeln();

    for (final table in schema.tables) {
      buffer.writeln('### ${table.name}');
      buffer.writeln();

      if (table.isPivot) {
        buffer.writeln('> **Pivot Table**');
        buffer.writeln();
      }

      buffer.writeln('| Column | Type | Constraints | Default |');
      buffer.writeln('|--------|------|-------------|---------|');

      for (final col in table.columns) {
        final constraints = col.constraints.join(', ');
        final defaultVal = col.defaultValue ?? '-';
        buffer.writeln(
          '| ${col.name} | ${col.displayType} | ${constraints.isEmpty ? '-' : constraints} | $defaultVal |',
        );
      }

      buffer.writeln();

      final relationships = schema.getRelationshipsForTable(table.name);
      if (relationships.isNotEmpty) {
        buffer.writeln('**Relationships:**');
        buffer.writeln();
        for (final rel in relationships) {
          final other = rel.sourceTable == table.name
              ? rel.targetTable
              : rel.sourceTable;
          final direction = rel.targetTable == table.name ? 'from' : 'to';
          buffer.writeln(
            '- ${rel.type.displayName} $direction **$other**${rel.hasPivot ? " (via ${rel.pivotTable})" : ""}',
          );
        }
        buffer.writeln();
      }

      if (table.indexes.isNotEmpty) {
        buffer.writeln('**Indexes:**');
        buffer.writeln();
        for (final idx in table.indexes) {
          buffer.writeln(
            '- `${idx.name}` on (${idx.columns.join(', ')})${idx.unique ? ' [UNIQUE]' : ''}',
          );
        }
        buffer.writeln();
      }

      buffer.writeln('---');
      buffer.writeln();
    }

    if (schema.relationships.isNotEmpty) {
      buffer.writeln('## Relationships');
      buffer.writeln();
      buffer.writeln('| Source | Type | Target | FK | Source | Inferred |');
      buffer.writeln('|--------|------|--------|-----|--------|----------|');

      for (final rel in schema.relationships) {
        buffer.writeln(
          '| ${rel.sourceTable} | ${rel.type.displayName} | ${rel.targetTable} | ${rel.foreignKey ?? '-'} | ${rel.localKey ?? '-'} | ${rel.isInferred ? "Yes" : "No"} |',
        );
      }

      buffer.writeln();
    }

    buffer.writeln('---');
    buffer.writeln();
    buffer.writeln('*Generated by Lumina ERD Studio*');

    return buffer.toString();
  }
}
